name: Image check on PR to develop

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: img_build_check
    if: |
      github.event.action == 'opened' &&
      github.event.pull_request.base.ref == 'develop' &&
      (
        contains(github.event.pull_request.files.*.filename, 'Dockerfile') ||
        contains(github.event.pull_request.files.*.filename, 'docker-compose.yaml')
      )

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Check for changes in Dockerfile or docker-compose.yaml within cluster_orchestrator directory
      - name: Find Dockerfile or docker-compose.yaml
        id: dockerfile
        run: |
          if [[ $(git diff --name-only ${{ github.event.before }} ${{ github.sha }}) =~ cluster_orchestrator/(.*\.)?(Dockerfile|docker-compose\.yaml) ]]; then
            echo "Changes found in Dockerfile or docker-compose.yaml"
            echo "::set-output name=changed::true"
          else
            echo "No changes found in Dockerfile or docker-compose.yaml"
            echo "::set-output name=changed::false"
          fi

      - name: Build Dockerfile or docker-compose.yaml
        if: steps.dockerfile.outputs.changed == 'true'
        run: |
          if [[ -f cluster_orchestrator/Dockerfile ]]; then
            docker build -t myimage:latest cluster_orchestrator/
          elif [[ -f cluster_orchestrator/docker-compose.yaml ]]; then
            docker-compose -f cluster_orchestrator/docker-compose.yaml build
          fi
