name: Trigger AWX Testbed on AWX Testbed Repository

on: [push, pull_request]


jobs:
  trigger-awx-repo-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Trigger GitHub Action on AWX Repository
        env:
          GITHUB_TOKEN: ${{ secrets.AWX_TRIGGER_PAT }} 
          REPO2_OWNER: 'TheDarkPyotr'         
          REPO2_NAME: 'ansible-tests'              
          TOPOLOGY_FILE: 'topology.json'  
          BRANCH: ${{ github.ref_name }}
          COMMIT: ${{ github.sha }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/$REPO2_OWNER/$REPO2_NAME/actions/workflows/on_push.yml/dispatches \
            -d '{"ref":"main", "inputs":{"topology":"'$TOPOLOGY_FILE'", "branch":"'$BRANCH'", "commit":"'$COMMIT'"}}'